name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: ssh_deploy

    steps:
    - uses: actions/checkout@v3
    - name: Push code update to server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete --exclude=.env"
          SOURCE: "src/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_WORKDIR }}/src
  
    - name: Push scripts update to server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "scripts/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_WORKDIR }}/scripts

    - uses: actions/cache@v2
      with:
        path: ~/frontend/node_modulus
        key: "${{ runner.os }}-frontend-${{ hashFiles('**/*node_modulus*') }}"
        restore-keys: |
          ${{ runner.os }}-frontend-

    - uses: actions/setup-node@v1
      with:
        node-version: '17'
        cache: 'npm'
    - run: npm install
      working-directory: frontend
    - run: npm run build
      working-directory: frontend

    - name: Push frontend update to server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "frontend/build"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_WORKDIR }}/frontend/build

    - name: Deploy
      env:
        WORKDIR: ${{ secrets.REMOTE_WORKDIR }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        envs: WORKDIR
        script_stop: true
        script: | 
          export WORKDIR=$WORKDIR
          bash ${{ secrets.REMOTE_WORKDIR }}/scripts/deploy.sh
